### ISSUE TITLE
what "sus" stuff did you find?

### ISSUE THREAD

**Issue by HausemasterIssue** [chrispycreme420/pyro-crack#1]
just curious.

**Comment by k0nnect** [comment]
don't look at my repositories from months ago they are retarded

**Comment by HausemasterIssue** [comment]
im genuinely curious, what "sus" stuff did you find tho?

**Comment by k0nnect** [comment]
can't remember since this was like 5-6 months ago, but it was most likely something i thought was malicious because i barely knew anything back then
